### PR TITLE
Upgrade to use elastic plugin extension v2

### PR DESCRIPTION
**Pull request by bdpiparva**
- [x] Need to decide on UI 

screen shot 2017-09-11 at 6 04 07 pm

screen shot 2017-09-11 at 6 32 25 pm

### CODE REVIEW

**Comment by ketan** [comment]
I like the table better since it shows everything without having to scan the page

**Comment by bdpiparva** [comment]
@ketan --- That is true and the better utilization of space.

**Comment by bdpiparva** [comment]
- UI improvements on status report

screen shot 2017-09-13 at 12 22 10 pm

**Comment by ketan** [comment]
Multiple issues:

screen shot 2017-09-13 at 4 28 32 pm

* indenting of `Leader` text is misplaced because of width of node id
* [Ascender](https://en.wikipedia.org/wiki/Ascender_(typography)) is cropped off in the header
* Say `Reachable: yes/no` instead of `Reachable: reachable`, use these icons http://fontawesome.io/icon/chain-broken/ http://fontawesome.io/icon/link/ if possible?

**Comment by ketan** [comment]
For some reason, the first accordion is always expanded.

**Pull request merged**
